// <auto-generated />
using System;
using CL2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CL2.Migrations
{
    [DbContext(typeof(CL2Context))]
    [Migration("20220816192730_listaIntegrantes")]
    partial class listaIntegrantes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CL2.Models.Administracion", b =>
                {
                    b.Property<int>("AdministracionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdministracionPeriodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PresidenteRepublica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdministracionID");

                    b.HasIndex("AdministracionPeriodo")
                        .IsUnique();

                    b.ToTable("Administracion");
                });

            modelBuilder.Entity("CL2.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("CL2.Models.Comision", b =>
                {
                    b.Property<int>("ComisionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreComision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SesionComisionID")
                        .HasColumnType("int");

                    b.Property<int>("TemaID")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComisionID");

                    b.HasIndex("SesionComisionID");

                    b.HasIndex("TemaID");

                    b.ToTable("Comision");
                });

            modelBuilder.Entity("CL2.Models.ComisionDiputados", b =>
                {
                    b.Property<int>("ComisionLegislativoID")
                        .HasColumnType("int");

                    b.Property<int>("DiputadoID")
                        .HasColumnType("int");

                    b.Property<string>("DetallePuesto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComisionLegislativoID", "DiputadoID");

                    b.HasIndex("DiputadoID");

                    b.ToTable("ComisionDiputados");
                });

            modelBuilder.Entity("CL2.Models.ComisionLegislativo", b =>
                {
                    b.Property<int>("ComisionLegislativoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComisionID")
                        .HasColumnType("int");

                    b.Property<int>("LegislativoID")
                        .HasColumnType("int");

                    b.HasKey("ComisionLegislativoID");

                    b.HasIndex("ComisionID");

                    b.HasIndex("LegislativoID");

                    b.ToTable("ComisionLegislativo");
                });

            modelBuilder.Entity("CL2.Models.ControlPolitico", b =>
                {
                    b.Property<int>("SesionPlenarioID")
                        .HasColumnType("int");

                    b.Property<int>("ControlPoliticoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DetalleComentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiputadoID")
                        .HasColumnType("int");

                    b.Property<string>("ResumenComentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemaID")
                        .HasColumnType("int");

                    b.HasKey("SesionPlenarioID", "ControlPoliticoID");

                    b.HasIndex("DiputadoID");

                    b.HasIndex("TemaID");

                    b.ToTable("ControlPolitico");
                });

            modelBuilder.Entity("CL2.Models.Diputado", b =>
                {
                    b.Property<int>("DiputadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorreoDiputado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneroDiputado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreDiputado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefonoDiputado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiputadoID");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Diputado");
                });

            modelBuilder.Entity("CL2.Models.DiscusionComision", b =>
                {
                    b.Property<int>("DiscusionComisionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SesionComisionActividadID")
                        .HasColumnType("int");

                    b.Property<int>("SesionComisionID")
                        .HasColumnType("int");

                    b.Property<string>("DetalleComentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiputadoID")
                        .HasColumnType("int");

                    b.Property<string>("ResumenComentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoComentario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiscusionComisionID", "SesionComisionActividadID", "SesionComisionID");

                    b.HasIndex("DiputadoID");

                    b.HasIndex("SesionComisionActividadID", "SesionComisionID");

                    b.ToTable("DiscusionComision");
                });

            modelBuilder.Entity("CL2.Models.DiscusionPlenario", b =>
                {
                    b.Property<int>("DiscusionPlenarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SesionPlenarioID")
                        .HasColumnType("int");

                    b.Property<int>("SesionPlenarioActividadID")
                        .HasColumnType("int");

                    b.Property<int>("DiputadoID")
                        .HasColumnType("int");

                    b.Property<string>("DiscusionDetalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscusionResumen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiscusionPlenarioID", "SesionPlenarioID", "SesionPlenarioActividadID");

                    b.HasIndex("DiputadoID");

                    b.HasIndex("SesionPlenarioID", "SesionPlenarioActividadID");

                    b.ToTable("DiscusionPlenario");
                });

            modelBuilder.Entity("CL2.Models.Fraccion", b =>
                {
                    b.Property<int>("FraccionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreFraccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SiglasFraccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FraccionID");

                    b.HasIndex("NombreFraccion")
                        .IsUnique();

                    b.ToTable("Fraccion");
                });

            modelBuilder.Entity("CL2.Models.IntegrantesPlenario", b =>
                {
                    b.Property<int>("PlenarioID")
                        .HasColumnType("int");

                    b.Property<int>("DiputadoID")
                        .HasColumnType("int");

                    b.Property<string>("Detalle_Puesto")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("FraccionID")
                        .HasColumnType("int");

                    b.Property<int?>("IntegrantesPlenarioDiputadoID")
                        .HasColumnType("int");

                    b.Property<int?>("IntegrantesPlenarioPlenarioID")
                        .HasColumnType("int");

                    b.HasKey("PlenarioID", "DiputadoID");

                    b.HasIndex("DiputadoID");

                    b.HasIndex("FraccionID")
                        .IsUnique()
                        .HasFilter("[FraccionID] IS NOT NULL");

                    b.HasIndex("IntegrantesPlenarioPlenarioID", "IntegrantesPlenarioDiputadoID");

                    b.ToTable("IntegrantesPlenario");
                });

            modelBuilder.Entity("CL2.Models.Legislativo", b =>
                {
                    b.Property<int>("LegislativoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdministracionID")
                        .HasColumnType("int");

                    b.Property<string>("AnnoLegislativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LegislativoID");

                    b.HasIndex("AdministracionID");

                    b.HasIndex("AnnoLegislativo")
                        .IsUnique();

                    b.ToTable("Legislativo");
                });

            modelBuilder.Entity("CL2.Models.Plenario", b =>
                {
                    b.Property<int>("PlenarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdministracionID")
                        .HasColumnType("int");

                    b.HasKey("PlenarioID");

                    b.HasIndex("AdministracionID")
                        .IsUnique();

                    b.ToTable("Plenario");
                });

            modelBuilder.Entity("CL2.Models.ProyectoDiputado", b =>
                {
                    b.Property<int>("ProyectoLeyID")
                        .HasColumnType("int");

                    b.Property<int>("DiputadoID")
                        .HasColumnType("int");

                    b.HasKey("ProyectoLeyID", "DiputadoID");

                    b.HasIndex("DiputadoID");

                    b.ToTable("ProyectoDiputado");
                });

            modelBuilder.Entity("CL2.Models.ProyectoLey", b =>
                {
                    b.Property<int>("ProyectoLeyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CantidadFirmas")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaPresentacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumeroExpediente")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TituloCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TituloCorto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProyectoLeyID");

                    b.ToTable("ProyectoLey");
                });

            modelBuilder.Entity("CL2.Models.ProyectoTema", b =>
                {
                    b.Property<int>("ProyectoLeyID")
                        .HasColumnType("int");

                    b.Property<int>("TemaID")
                        .HasColumnType("int");

                    b.HasKey("ProyectoLeyID", "TemaID");

                    b.HasIndex("TemaID");

                    b.ToTable("ProyectoTema");
                });

            modelBuilder.Entity("CL2.Models.SesionComision", b =>
                {
                    b.Property<int>("SesionComisionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComisionLegislativoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSesionComision")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LegislativoID")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSesionComision")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PeriodoSesionComision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSesionComision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SesionComisionID");

                    b.HasIndex("LegislativoID");

                    b.HasIndex("ComisionLegislativoID", "NumeroSesionComision")
                        .IsUnique();

                    b.ToTable("SesionComision");
                });

            modelBuilder.Entity("CL2.Models.SesionComisionActividad", b =>
                {
                    b.Property<int>("SesionComisionActividadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SesionComisionID")
                        .HasColumnType("int");

                    b.Property<string>("DecisionMocion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetalleActividad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiputadoID")
                        .HasColumnType("int");

                    b.Property<string>("NumeroMocion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProyectoLeyID")
                        .HasColumnType("int");

                    b.Property<int?>("TipoActividadComisionesTipoActividadComisionID")
                        .HasColumnType("int");

                    b.Property<int>("TipoActividadID")
                        .HasColumnType("int");

                    b.Property<string>("TipoMocion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VotosContraDictamen")
                        .HasColumnType("int");

                    b.Property<int>("VotosFavorDictamen")
                        .HasColumnType("int");

                    b.HasKey("SesionComisionActividadID", "SesionComisionID");

                    b.HasIndex("DiputadoID");

                    b.HasIndex("ProyectoLeyID");

                    b.HasIndex("SesionComisionID");

                    b.HasIndex("TipoActividadComisionesTipoActividadComisionID");

                    b.ToTable("SesionComisionActividad");
                });

            modelBuilder.Entity("CL2.Models.SesionPlenario", b =>
                {
                    b.Property<int>("SesionPlenarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("FechaSesionPlenario")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroSesion")
                        .HasColumnType("int");

                    b.Property<string>("PeriodoSesionPlenario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlenarioID")
                        .HasColumnType("int");

                    b.Property<string>("TipoSesionPlenario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SesionPlenarioID");

                    b.HasIndex("PlenarioID", "NumeroSesion")
                        .IsUnique();

                    b.ToTable("SesionPlenario");
                });

            modelBuilder.Entity("CL2.Models.SesionPlenarioActividad", b =>
                {
                    b.Property<int>("SesionPlenarioID")
                        .HasColumnType("int");

                    b.Property<int>("SesionPlenarioActividadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DecisionMocion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetalleActividadPlenario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiputadoID")
                        .HasColumnType("int");

                    b.Property<string>("NumeroMocion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProyectoLeyID")
                        .HasColumnType("int");

                    b.Property<int>("TipoActividadPlenarioID")
                        .HasColumnType("int");

                    b.Property<string>("TipoDebate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMocion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VotosContraDebate")
                        .HasColumnType("int");

                    b.Property<int>("VotosFavorDebate")
                        .HasColumnType("int");

                    b.HasKey("SesionPlenarioID", "SesionPlenarioActividadID");

                    b.HasIndex("DiputadoID");

                    b.HasIndex("ProyectoLeyID");

                    b.HasIndex("TipoActividadPlenarioID");

                    b.ToTable("SesionPlenarioActividad");
                });

            modelBuilder.Entity("CL2.Models.Tema", b =>
                {
                    b.Property<int>("TemaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TemaDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TemaID");

                    b.HasIndex("TemaDesc")
                        .IsUnique();

                    b.ToTable("Tema");
                });

            modelBuilder.Entity("CL2.Models.TipoActividadComision", b =>
                {
                    b.Property<int>("TipoActividadComisionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DetalleActividadComision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoActividadComisionID");

                    b.ToTable("TipoActividadComision");
                });

            modelBuilder.Entity("CL2.Models.TipoActividadPlenario", b =>
                {
                    b.Property<int>("TipoActividadPlenarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DetalleActividadPlenario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoActividadPlenarioID");

                    b.ToTable("TipoActividadPlenario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CL2.Models.Comision", b =>
                {
                    b.HasOne("CL2.Models.SesionComision", "SesionComision")
                        .WithMany()
                        .HasForeignKey("SesionComisionID");

                    b.HasOne("CL2.Models.Tema", "Tema")
                        .WithMany("Comision")
                        .HasForeignKey("TemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SesionComision");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("CL2.Models.ComisionDiputados", b =>
                {
                    b.HasOne("CL2.Models.ComisionLegislativo", "ComisionLegislativo")
                        .WithMany("ComisionDiputados")
                        .HasForeignKey("ComisionLegislativoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.Diputado", "Diputado")
                        .WithMany("ComisionDiputados")
                        .HasForeignKey("DiputadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComisionLegislativo");

                    b.Navigation("Diputado");
                });

            modelBuilder.Entity("CL2.Models.ComisionLegislativo", b =>
                {
                    b.HasOne("CL2.Models.Comision", "Comision")
                        .WithMany("ComisionLegislativos")
                        .HasForeignKey("ComisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.Legislativo", "Legislativo")
                        .WithMany("ComisionLegislativo")
                        .HasForeignKey("LegislativoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comision");

                    b.Navigation("Legislativo");
                });

            modelBuilder.Entity("CL2.Models.ControlPolitico", b =>
                {
                    b.HasOne("CL2.Models.Diputado", "Diputados")
                        .WithMany("ControlPolitico")
                        .HasForeignKey("DiputadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.SesionPlenario", "SesionPlenario")
                        .WithMany("ControlPolitico")
                        .HasForeignKey("SesionPlenarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.Tema", "Temas")
                        .WithMany("ControlPolitico")
                        .HasForeignKey("TemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diputados");

                    b.Navigation("SesionPlenario");

                    b.Navigation("Temas");
                });

            modelBuilder.Entity("CL2.Models.DiscusionComision", b =>
                {
                    b.HasOne("CL2.Models.Diputado", "Diputado")
                        .WithMany("DiscusionComision")
                        .HasForeignKey("DiputadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.SesionComisionActividad", "SesionComisionActividades")
                        .WithMany("DiscusionComision")
                        .HasForeignKey("SesionComisionActividadID", "SesionComisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diputado");

                    b.Navigation("SesionComisionActividades");
                });

            modelBuilder.Entity("CL2.Models.DiscusionPlenario", b =>
                {
                    b.HasOne("CL2.Models.Diputado", "Diputado")
                        .WithMany("DiscusionPlenarios")
                        .HasForeignKey("DiputadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.SesionPlenarioActividad", "SesionPlenarioActividad")
                        .WithMany("DiscusionPlenario")
                        .HasForeignKey("SesionPlenarioID", "SesionPlenarioActividadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diputado");

                    b.Navigation("SesionPlenarioActividad");
                });

            modelBuilder.Entity("CL2.Models.IntegrantesPlenario", b =>
                {
                    b.HasOne("CL2.Models.Diputado", "Diputado")
                        .WithMany("IntegrantesPlenarios")
                        .HasForeignKey("DiputadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.Fraccion", "Fraccion")
                        .WithOne("IntegrantesPlenario")
                        .HasForeignKey("CL2.Models.IntegrantesPlenario", "FraccionID");

                    b.HasOne("CL2.Models.Plenario", "Plenario")
                        .WithMany("IntegrantesPlenarios")
                        .HasForeignKey("PlenarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.IntegrantesPlenario", null)
                        .WithMany("integrantesPlenariosLista")
                        .HasForeignKey("IntegrantesPlenarioPlenarioID", "IntegrantesPlenarioDiputadoID");

                    b.Navigation("Diputado");

                    b.Navigation("Fraccion");

                    b.Navigation("Plenario");
                });

            modelBuilder.Entity("CL2.Models.Legislativo", b =>
                {
                    b.HasOne("CL2.Models.Administracion", "Administracion")
                        .WithMany("Legislativos")
                        .HasForeignKey("AdministracionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administracion");
                });

            modelBuilder.Entity("CL2.Models.Plenario", b =>
                {
                    b.HasOne("CL2.Models.Administracion", "Administracion")
                        .WithOne("Plenario")
                        .HasForeignKey("CL2.Models.Plenario", "AdministracionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administracion");
                });

            modelBuilder.Entity("CL2.Models.ProyectoDiputado", b =>
                {
                    b.HasOne("CL2.Models.Diputado", "Diputado")
                        .WithMany("ProyectosDiputado")
                        .HasForeignKey("DiputadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.ProyectoLey", "ProyectosLey")
                        .WithMany("ProyectoDiputado")
                        .HasForeignKey("ProyectoLeyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diputado");

                    b.Navigation("ProyectosLey");
                });

            modelBuilder.Entity("CL2.Models.ProyectoTema", b =>
                {
                    b.HasOne("CL2.Models.ProyectoLey", "ProyectosLey")
                        .WithMany("TemasProyectos")
                        .HasForeignKey("ProyectoLeyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.Tema", "Tema")
                        .WithMany("TemasProyecto")
                        .HasForeignKey("TemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProyectosLey");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("CL2.Models.SesionComision", b =>
                {
                    b.HasOne("CL2.Models.ComisionLegislativo", "ComisionLegislativos")
                        .WithMany("SesionComision")
                        .HasForeignKey("ComisionLegislativoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.Legislativo", null)
                        .WithMany("SesionComision")
                        .HasForeignKey("LegislativoID");

                    b.Navigation("ComisionLegislativos");
                });

            modelBuilder.Entity("CL2.Models.SesionComisionActividad", b =>
                {
                    b.HasOne("CL2.Models.Diputado", "Diputado")
                        .WithMany("SesionComisionActividad")
                        .HasForeignKey("DiputadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.ProyectoLey", "ProyectosLey")
                        .WithMany("SesionComisionActividad")
                        .HasForeignKey("ProyectoLeyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.SesionComision", "SesionComisiones")
                        .WithMany("SesionComisionActividad")
                        .HasForeignKey("SesionComisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.TipoActividadComision", "TipoActividadComisiones")
                        .WithMany("SesionComisionActividad")
                        .HasForeignKey("TipoActividadComisionesTipoActividadComisionID");

                    b.Navigation("Diputado");

                    b.Navigation("ProyectosLey");

                    b.Navigation("SesionComisiones");

                    b.Navigation("TipoActividadComisiones");
                });

            modelBuilder.Entity("CL2.Models.SesionPlenario", b =>
                {
                    b.HasOne("CL2.Models.Plenario", "Plenario")
                        .WithMany("SesionPlenarios")
                        .HasForeignKey("PlenarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plenario");
                });

            modelBuilder.Entity("CL2.Models.SesionPlenarioActividad", b =>
                {
                    b.HasOne("CL2.Models.Diputado", "Diputado")
                        .WithMany("SesionPlenarioActividad")
                        .HasForeignKey("DiputadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.ProyectoLey", "ProyectoLey")
                        .WithMany("SesionPlenarioActividad")
                        .HasForeignKey("ProyectoLeyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.SesionPlenario", "SesionPlenario")
                        .WithMany("SesionPlenarioActividad")
                        .HasForeignKey("SesionPlenarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.TipoActividadPlenario", "TipoActividadPlenario")
                        .WithMany("SesionPlenarioActividad")
                        .HasForeignKey("TipoActividadPlenarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diputado");

                    b.Navigation("ProyectoLey");

                    b.Navigation("SesionPlenario");

                    b.Navigation("TipoActividadPlenario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CL2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CL2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CL2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CL2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CL2.Models.Administracion", b =>
                {
                    b.Navigation("Legislativos");

                    b.Navigation("Plenario");
                });

            modelBuilder.Entity("CL2.Models.Comision", b =>
                {
                    b.Navigation("ComisionLegislativos");
                });

            modelBuilder.Entity("CL2.Models.ComisionLegislativo", b =>
                {
                    b.Navigation("ComisionDiputados");

                    b.Navigation("SesionComision");
                });

            modelBuilder.Entity("CL2.Models.Diputado", b =>
                {
                    b.Navigation("ComisionDiputados");

                    b.Navigation("ControlPolitico");

                    b.Navigation("DiscusionComision");

                    b.Navigation("DiscusionPlenarios");

                    b.Navigation("IntegrantesPlenarios");

                    b.Navigation("ProyectosDiputado");

                    b.Navigation("SesionComisionActividad");

                    b.Navigation("SesionPlenarioActividad");
                });

            modelBuilder.Entity("CL2.Models.Fraccion", b =>
                {
                    b.Navigation("IntegrantesPlenario");
                });

            modelBuilder.Entity("CL2.Models.IntegrantesPlenario", b =>
                {
                    b.Navigation("integrantesPlenariosLista");
                });

            modelBuilder.Entity("CL2.Models.Legislativo", b =>
                {
                    b.Navigation("ComisionLegislativo");

                    b.Navigation("SesionComision");
                });

            modelBuilder.Entity("CL2.Models.Plenario", b =>
                {
                    b.Navigation("IntegrantesPlenarios");

                    b.Navigation("SesionPlenarios");
                });

            modelBuilder.Entity("CL2.Models.ProyectoLey", b =>
                {
                    b.Navigation("ProyectoDiputado");

                    b.Navigation("SesionComisionActividad");

                    b.Navigation("SesionPlenarioActividad");

                    b.Navigation("TemasProyectos");
                });

            modelBuilder.Entity("CL2.Models.SesionComision", b =>
                {
                    b.Navigation("SesionComisionActividad");
                });

            modelBuilder.Entity("CL2.Models.SesionComisionActividad", b =>
                {
                    b.Navigation("DiscusionComision");
                });

            modelBuilder.Entity("CL2.Models.SesionPlenario", b =>
                {
                    b.Navigation("ControlPolitico");

                    b.Navigation("SesionPlenarioActividad");
                });

            modelBuilder.Entity("CL2.Models.SesionPlenarioActividad", b =>
                {
                    b.Navigation("DiscusionPlenario");
                });

            modelBuilder.Entity("CL2.Models.Tema", b =>
                {
                    b.Navigation("Comision");

                    b.Navigation("ControlPolitico");

                    b.Navigation("TemasProyecto");
                });

            modelBuilder.Entity("CL2.Models.TipoActividadComision", b =>
                {
                    b.Navigation("SesionComisionActividad");
                });

            modelBuilder.Entity("CL2.Models.TipoActividadPlenario", b =>
                {
                    b.Navigation("SesionPlenarioActividad");
                });
#pragma warning restore 612, 618
        }
    }
}
